import numpy as np
import matplotlib.pyplot as plt
from matplotlib import colors as mcolors
colors = dict(mcolors.BASE_COLORS, **mcolors.CSS4_COLORS)
plt.close('all')
by_hsv = sorted((tuple(mcolors.rgb_to_hsv(mcolors.to_rgba(color)[:3])), name)
                for name, color in colors.items())
colorNames = [name for hsv, name in by_hsv]
# colorNames.index('blue')

resultsSVM = np.load('NER_SVM.npy')
averageSVM = np.mean(resultsSVM,0)
resultsELM = np.load('NER_ELM.npy')
averageELM = np.mean(resultsELM,0)

x = np.arange(1, 16, 1)
# Plot the results
plt.figure(1)
plt.subplot(121)
plt.plot(x, averageSVM[3,:], linestyle='--', marker='p', markersize=7, linewidth=2.8, color=colorNames[123])
plt.plot(x, averageSVM[5,:], linestyle='--', marker='*', markersize=7, linewidth=2.8, color=colorNames[153])
plt.plot(x, averageSVM[1,:], linestyle='--', marker='o', markersize=7, linewidth=2.8, color=colorNames[65])
plt.plot(x, averageELM[3,:], linestyle=':', marker='p', markersize=7, linewidth=2.8, color=colorNames[128])
plt.plot(x, averageELM[5,:], linestyle=':', marker='*', markersize=7, linewidth=2.8, color=colorNames[24])
plt.plot(x, averageELM[1,:], linestyle=':', marker='o', markersize=7, linewidth=2.8, color=colorNames[82])
plt.title('ASL', fontsize=18)
plt.ylabel('Accuracy', fontsize=18)
plt.xlabel('Number of Synergies', fontsize=14)
plt.text(0.19, 0.03, 'a) ASL Classification', fontsize=18, transform=plt.gcf().transFigure)
plt.xticks(np.arange(0, 16, step=1))
plt.yticks(np.arange(0, 0.95, step=.1))
plt.grid(True)
plt.subplot(122)
plt.plot(x, averageSVM[2,:], linestyle='--', marker='p', markersize=7, linewidth=2.8, color=colorNames[123])
plt.plot(x, averageSVM[0,:], linestyle='--', marker='*', markersize=7, linewidth=2.8, color=colorNames[153])
plt.plot(x, averageSVM[4,:], linestyle='--', marker='o', markersize=7, linewidth=2.8, color=colorNames[65])
plt.plot(x, averageELM[2,:], linestyle=':', marker='p', markersize=7, linewidth=2.8, color=colorNames[128])
plt.plot(x, averageELM[0,:], linestyle=':', marker='*', markersize=7, linewidth=2.8, color=colorNames[24])
plt.plot(x, averageELM[4,:], linestyle=':', marker='o', markersize=7, linewidth=2.8, color=colorNames[82])
plt.title('Grasp', fontsize=18)
plt.text(0.70, 0.03, 'b) Grasp Classification', fontsize=18, transform=plt.gcf().transFigure)
plt.ylabel('Accuracy', fontsize=18)
plt.xlabel('Number of Synergies', fontsize=14)
plt.xticks(np.arange(0, 16, step=1))
plt.yticks(np.arange(0, 0.95, step=.1))
plt.figlegend(['Free - SVM', 'Grasp - SVM', 'ASL - SVM', 'Free - ELM', 'Grasp - ELM', 'ASL - ELM'], loc =9, bbox_to_anchor=(0.5,0.89))
plt.subplots_adjust(left=0.04, right=0.98)
plt.grid(True)
plt.show()

